# Generated by Django 4.1.7 on 2023-04-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Enter a description for the genre', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.CharField(help_text='Enter the description', max_length=400),
        ),
        migrations.AddField(
            model_name='quote',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.genre'),
        ),
    ]
